### ISSUE TITLE
DuplicateFileException: Duplicate files copied in APK META-INF/INDEX.LIST

### ISSUE THREAD

**Issue by pykaso** [Matthias247/jawampa#94] opened 2016-10-06 22:00 UTC
Hi,  I added dependency to jawampa to my Android project. Now I'm getting this error.

Dep:
compile 'ws.wamp.jawampa:jawampa-netty:0.4.2'

Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/INDEX.LIST
>     File1: /Users/lgergel/.gradle/caches/modules-2/files-2.1/io.netty/netty-buffer/4.0.24.Final/86b0544a2ad9c647894dd460abcd8806da08f5d4/netty-buffer-4.0.24.Final.jar
>     File2: /Users/lgergel/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport/4.0.24.Final/95689eb79181ecd96592b0217fe4af0aca143d5/netty-transport-4.0.24.Final.jar
>     File3: /Users/lgergel/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http/4.0.24.Final/aa59de3ada353518026f869bb89b71064f65911e/netty-codec-http-4.0.24.Final.jar
>     File4: /Users/lgergel/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler/4.0.24.Final/a5d1c44bbfab44cb45987ebf31904c32250e2e80/netty-handler-4.0.24.Final.jar
>     File5: /Users/lgergel/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec/4.0.24.Final/862a801978d25197ae44292337aabf26c6703b9e/netty-codec-4.0.24.Final.jar
>     File6: /Users/lgergel/.gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.0.24.Final/60c06ba48277374ac1e75ad8edabd40d0d91586c/netty-common-4.0.24.Final.jar

**Comment by Alebat** [comment] 2016-12-12 11:44
Same error

**Comment by Alebat** [comment] 2016-12-12 14:25
I solved my problem:
I import jawampa in an android library, as the error comes from the APK generation I added the following options in the build.gradle file of the **main application**, not in the library's:
```
android{
    packagingOptions {
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/io.netty.versions.properties'
    }
}
```

**Comment by zigeH** [comment] 2017-04-24 00:31
thanks! I spent 3hours on this problem!

**Comment by Matthias247** [comment] 2017-05-17 23:30
I'm closing this one, since it seems the issue is a dependency conflict within the application that can only only be resolved by the app developer. If there's a specific improvement for jawampa that needs to be made feel free to open a new issue.

**Closed by Matthias247** 2017-05-17 23:30 UTC
